
CREATE TABLE `User` (
	`user_id`	VARCHAR(100)	NOT NULL AUTO_INCREMENT PRIMARY KEY	COMMENT '사용자ID',
	`password`	VARCHAR(255)	NOT NULL	COMMENT '비밀번호',
	`name`	VARCHAR(100)	NOT NULL	COMMENT '이름',
	`email`	VARCHAR(100)	NOT NULL	COMMENT '이메일',
	`phone`	VARCHAR(15)	NULL	COMMENT '전화번호'
);


SELECT* FROM User;



DROP TABLE User;